apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgAuKmvatci97UjFMdsCuDKyuZIKUtYcMUQ3KaZcI+MpWqbyRfl/GCXupmClbpO8GOTZqH6r/jntKgsA4x45SanGvqJ5O2kazNYqXa4pzTPQfuCjo1uTnaDtPeHaLr/IIauMb0KKQ9BUUMc9IimfTWJZ6WpU3sI1igWYoyW7r9S2tfdj05vq6unu4klTc7dwr/ljS5s8v0+IuWnF07n+hqH8IK0SKUBTDYXjrzwGcPOazXR9QjyESQaCNub+JUXFcBYU1ySnvEZrVZMa0ExKtzYxu8ixUzzC8XSgihjGR9rQPw1hR/bhF9lz7Xpx4kzayjPPTGQUnwDBH1ypcWsK8Os5y6Pz+ADRlLbl2DNaqYHH9l1cWnDIkUaSKgXq3SIWSkIXqTY1FST445DXlLHGXmL2fDkjiVUNYqE7dPP9H+M9n/4Mrz8QQetE8rSyNJIWnj5Fh82mzQSOoxHI2SiVh3ILKApNl+CS/PDdgB2m2oP5nAhsGg3xhrP1IhY838O/8ZHJmXohEfJXInxFuP2XQYMyEOcQ76o7E2N6e+D+DC26ur+CVOEEK+d+j6hUsBYjt3BxSRDygLiI4z2CRRWbXFAKJ/ssajcw1j+H3zSuGNXHPYlfWrR/oCosSHWQlpA9LVMEZ+SXnflVfBp2qZ15j1r2mAWFs0SB2ItxcBCkwSuuaOi9J6yesd0Op3FehDA2FqjpfPS50cYBWMA=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app


