apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgA7tTynstkGU8GFW81vaAqzXDeNj//nJ2osjNlcuRUBR/RaR4rXqsBENyssu+wI/YY0oRlw3W5JxmtFimWqcwvL6lOrC2gHYmy3QMm/4Uy6qjgdNYbG2MUFpIet+csb656WgeNo6UdEDsKz5/83vDEvIRCVHze/9LYBjMci5UI0vznfypjsJpzyMcAusfLvm+K/cOmp5orO5qk3dXnxVO0VA1ECHmfPQXj4W6vZphXeODzzyD9zkjQjVKTFpNdwN2yTuDoz1kamFOOOHDsyUWISP/DvNa0FrpykYWg8SfK3jLhOO2Sjpft/WRBKYvnNCk6TXxKVm2f3OoEdCunIj0qRtCkAGEbAHlmZ6kY0VzQJFQdFx8gkiyfhTBEIJqHHe0hCt7w0BS4rN51POF8hATNPlHUsK9vKqAZ3R5jAoEAOV61mskoOjD3o2ttMOx2tetr+bQyzXPGrLoPfu0flSc2me+vdIrM3gUwQhs1Y1G89imdeJtG/qRr8GRwrVYrO1mc7MxjxrfSHztulnoDMfUdmoQHM/tC0sp45ladqdMZ7/t3OAvYRXNwVic2AzfiiJezAVPKz7dx0TqpI00VomVbHrMt/6U7p9R9o94r8uCKulIvrkhfzsZeVNeREc5r8vr0rP9mP4niuXluYg9oNfPuzorOw+DspgTR5d1gUWFHd11HBVz7aNeCmn1F9m9ctDH1XozLUTYcW
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

