apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgBDzHvP3G11og3XSkfygF+lX3jN0kGdIu2xOpur1hr7e8ol4ZLqcNdId/G1JHKvSj+FQzBcdkyCld0sMrZ+yuhqVTsNtH3KGpN1W0pKHMZXosW6WtYSxsdJQUu6Pl4Mmvuu/RnUCt5sIsonO9pfzB39b6bPXRTcYa3yVqXrX/oXflz//D3DjYB5Pl1KoLbUE7li6q/eDFE3pEJm/WW0TQlM0Ol4yLcCd0t22deDJJbQ5ljNti6gfCTjwOKqmSGT3gaU/V5AUQT1CJQZIlgsmo4PbKGqBtEFehyQayXa/TZNdJ9M2wAwD7lpJVItOLR/1KAOhXNIPtkhRKWydmvJlOZ5KIa1YrVU9uDxEaYy97C1idKw+B/5eodHRqdI9R2/w30xNAL+mB5mW78t2xbyInZ+FiGuQtFDt7/6q3I7TmH4T6FTf3pzuXpRBnYDPgz4gIBy4oMmAgwhfxJAaqj7c/YHQu464qZpd6uS4RUowGwsJGpipkJcR3yLAo6Tnn67GLVnBIH70+O0x13TLChBk1gOTjQrHCf/Sb7mfv7K8+PGbb7zZrcFwge+841k3p29GgtoZQzc1++fX86gTQQgFfTo3Feya6W8UgMm/jmW+7uKLYX0ueDtqasd2OTnnAAytBfUBgjWKf2qqKEvXevJBh71SmHIBQFZf7Pd3k/U1pZ9uHshPiRQsHRLwCPk5RjakqDosiASHrrqywN/
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

