apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgCC70NS8giTF8o7SOtUJCYuI1OXygcNQnldHX73ynOHnyulQN2OhDx/BCyrwrFZY9vJOf3tMZmDzeHAYfNMs1wODCkZuvU3FBbWx5KxPkI3rV01V42MnKdomXSZpZVQHga4GGJkgbZ5pTYzCtBFmHoH7dOE0wSi6nyGFi1gPaYPApjgEVGWp8K4ceKnPrwUbJDYuKLM/b6HQOTVh91rSGNiOBMN8Rqd+z1cJAYqB2p18upFotM2WnNN1EsHoYhBzv1ykGktpPodoxeYV+XIzg7NDwJm4CsF8X+wCviC6r7V9Jz8g+us1V4vhYJetdodVlhhlMt21+3hICmNidsFLWpRh3UwJAasPxxJq4rfhTTulzi9ymHx0bPrNWOLRa7oPryxGXiz8cL2jlIw0ilXBOQDm8ioxLZtnzbSM74sHy+QJu3KKmapBCdvE6lHiLKKyzkTvc7UkB41sUENMB1Zcb1I7T63PEwiqi0eK6/iWMy7CHlqrorBM/gr8dCBBjkNjyQzeETvz2MZZj7RHI3Ny+9PEvFuBjPdC5Plc1EddtdHUQE+DNWI3uEva/fnSBg8B46gmNN8BEXlFqf7qL5OR1Q+xO+MTSyTbj6BB7v+7jBlGtUkH8QEH3S1BJzsKZHtHNAcD0Ev4QTkP6NmbfNMIvVgS6lVOrOPPvsH2VYoIlqMrgp0BZZw7l8y6Br5YoJf0hRi3AS3W0QvQLDV
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

