apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgAfu95anHuh6FaQiNSXNDAZ4n7DqAdhZTGXQXElyp9lus1PS/MkclBVNEhDg9zC7P73heWQXeJj7dcBk6Dth3w0IhRofVjjLPpiH+a3dE7Mmi58jPMxwahhwGGkQvn+ZqFc6DyxajgzkokDpic4vaIHKMMQCWPy8W8clcc1XfIPh1W8pLlsXF7vX1GmC9OPi9m3YwO7Y1hgYgc+9gwnptLYcp7Xc0QVu7mJpSk9WPVnLdXUdydttHBRyygWqBvIG/iJORyWbjS9BorkY68Y9jwbgVkyn8PF9VcVWy3TgVOcH9kuolohQr8Nw9pLRwEyGj8euRSxMdbGLKRem4eQkbxgoFcXAA3WBWMDtoVJ8dP+RMgNUA9BoNUl31nQS4myAn3I4m/q4iE+Yp4ngL2uCZWoCfd2QKCUOZGkEDKKZjyU25zs11x/5dffjd5gWoEfNRYUiBSAiywhcFbvK3PPYFR4a32f6/5yZaB/KHoC1jUWS/Ns5WRpb9++/cDUKQKKnXD5dr6eJKJQx1w1xNDyqoSjviACe2zc/amMkJnErVhfnY/3sluPgZ47FyPZXVwgA219SJ+5XrQmpy0g5zR6ZkJi4MkIf5duZQx07bEupWLg8D0bd9HggyDT9TQYYdlkK00Ijpv5a0vqDYlG1CI3RYmLn2U/cA3GM5LJ0gQqzjBQ+eEL5uIETXNko/5CEjmUiJMQwGsDH0Xd
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

