apiVersion: v1
kind: Pod
metadata:
  name: demo-app2
  namespace: demo-app2
  labels:
    app: demo-app
spec:
  containers:
  - image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - cat /tmp/mysecret/secret;
        sleep 3600
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - name: mysecretvol
        mountPath: "/tmp/mysecret"
        readOnly: true
  volumes:
  - name: mysecretvol
    secret:
      secretName: mysecret
